# Site
title: 无辄的栈
description: Junior | Programmer | Reader | Film Lover | Runner
url: https://www.imwzk.com
logo: https://pic.imwzk.com/author.jpg                                       # Site logo
locale: zh_CN
license: 赣ICP备19012492号
wechat_pic: https://pic.imwzk.com/wechat-white.png
display_rss:  true  # set this to `false` to hide rss icon
enable_pangu: true  # pangu will automatically insert spaces between English and Chinese

# Left Block Images
background:
  homepage: https://pic.imwzk.com/home.png                           # this image will be shown on homepage's left block
  post-list: https://pic.imwzk.com/post-list.jpg             # this image will be shown on post list page
  default-post: https://pic.imwzk.com/default-post.jpg   # this image will be shown when post's front matter doesn't specify any image

# Article Comments with Gitalk
gitalk:
  enabled: true
  client_id: 541b66df2ca4fba90b0c
  client_secret: 157f686855f29762873e8ce11e056f7397c58209
  repository: keithnull.github.io
  owner: keithnull
  admin: keithnull

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-118116525-1

# Social Links
email:             hi@imwzk.com
#google.plus:        username
twitter:            _keithnull
#facebook:           username
github:             keithnull
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
